stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: tux/fact_extractor
      pushRemote: true
      registry: 127.0.0.1:34579
timeout: 60
notification: {}
