stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: saltmine/fact_extractor
      pushRemote: true
      registry: http://registry.k8s.saltmine.dev:5000
timeout: 60
notification:
  recipients:
  - recipient: '#homelab'
    notifier: c-lp2n8:n-bdfx9
  condition:
  - Success
  - Changed
  - Failed
