stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: tux/fact_extractor
      pushRemote: true
      registry: 10.43.182.243:5000
timeout: 60
notification: {}
